/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as HrCandidatesRouteImport } from './routes/hr.candidates'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrProcessIdRouteImport } from './routes/hr.process.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrRoute,
} as any)
const HrCandidatesRoute = HrCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => HrRoute,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => HrRoute,
} as any)
const HrProcessIdRoute = HrProcessIdRouteImport.update({
  id: '/process/$id',
  path: '/process/$id',
  getParentRoute: () => HrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/onboarding': typeof OnboardingRoute
  '/hr': typeof HrRouteWithChildren
  '/login': typeof LoginRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/': typeof HrIndexRoute
  '/hr/process/$id': typeof HrProcessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof LoginRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr': typeof HrIndexRoute
  '/hr/process/$id': typeof HrProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/onboarding': typeof OnboardingRoute
  '/hr': typeof HrRouteWithChildren
  '/login': typeof LoginRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/': typeof HrIndexRoute
  '/hr/process/$id': typeof HrProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/onboarding'
    | '/hr'
    | '/login'
    | '/hr/candidates'
    | '/hr/payroll'
    | '/hr/'
    | '/hr/process/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/onboarding' | '/login' | '/hr/candidates' | '/hr/payroll' | '/hr' | '/hr/process/$id'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/onboarding'
    | '/hr'
    | '/login'
    | '/hr/candidates'
    | '/hr/payroll'
    | '/hr/'
    | '/hr/process/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  OnboardingRoute: typeof OnboardingRoute
  HrRoute: typeof HrRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/candidates': {
      id: '/hr/candidates'
      path: '/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/process/$id': {
      id: '/hr/process/$id'
      path: '/process/$id'
      fullPath: '/hr/process/$id'
      preLoaderRoute: typeof HrProcessIdRouteImport
      parentRoute: typeof HrRoute
    }
  }
}

interface HrRouteChildren {
  HrCandidatesRoute: typeof HrCandidatesRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrIndexRoute: typeof HrIndexRoute
  HrProcessIdRoute: typeof HrProcessIdRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrCandidatesRoute: HrCandidatesRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrIndexRoute: HrIndexRoute,
  HrProcessIdRoute: HrProcessIdRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  OnboardingRoute: OnboardingRoute,
  HrRoute: HrRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
